BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id TEXT;
CREATE TABLE IF NOT EXISTS governed_messages(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,mailbox_id TEXT NOT NULL,external_id TEXT NOT NULL,thread_id TEXT NOT NULL,sender TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,received_at TIMESTAMPTZ NOT NULL,source_checksum CHAR(64) NOT NULL,prompt_injection_suspected BOOLEAN NOT NULL DEFAULT FALSE,status TEXT NOT NULL DEFAULT 'quarantined' CHECK(status IN('quarantined','triaged','archived')),classification JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,mailbox_id,external_id));
CREATE TABLE IF NOT EXISTS governed_drafts(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,message_id BIGINT NOT NULL REFERENCES governed_messages(id),recipients JSONB NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,grounding JSONB NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','pending_approval','approved','rejected','queued','sent','failed')),version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,approved_by TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS email_send_outbox(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,draft_id BIGINT NOT NULL UNIQUE REFERENCES governed_drafts(id),payload JSONB NOT NULL,status TEXT NOT NULL CHECK(status IN('pending_provider_delivery','delivering','delivered','failed','dead_letter')),provider_message_id TEXT,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS triage_dispositions(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,message_id BIGINT NOT NULL REFERENCES governed_messages(id),actor_id TEXT NOT NULL,disposition TEXT NOT NULL,correction JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS email_triage_events(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,actor_id TEXT NOT NULL,subject_type TEXT NOT NULL,subject_id TEXT NOT NULL,event_type TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS governed_message_queue_idx ON governed_messages(tenant_id,status,received_at DESC);
COMMIT;
