const crypto=require('crypto');
class TriageError extends Error{constructor(message,code='INVALID_TRIAGE_WORKFLOW'){super(message);this.code=code;}}
const clean=(v,n,max=5000)=>{const s=String(v||'').trim();if(!s)throw new TriageError(`${n} is required`);if(s.length>max)throw new TriageError(`${n} is too long`);return s;};
const INJECTION_PATTERNS=[/ignore (all|any|the) previous instructions/i,/system prompt/i,/reveal (your|the) secrets?/i,/tool[_ -]?call/i,/send (this|an) email to/i];
function inspectUntrustedContent(value){const text=String(value||'');return{prompt_injection_suspected:INJECTION_PATTERNS.some(r=>r.test(text)),redacted:text.replace(/\b(?:api[_-]?key|password|secret|token)\s*[:=]\s*\S+/gi,'[REDACTED]')};}
function validateInbound(input){const externalId=clean(input.external_id,'external_id',500),mailbox=clean(input.mailbox_id,'mailbox_id',200),from=clean(input.from,'from',320),subject=clean(input.subject,'subject',1000),body=clean(input.body,'body',100000);const scan=inspectUntrustedContent(`${subject}\n${body}`);return{external_id:externalId,mailbox_id:mailbox,thread_id:clean(input.thread_id||externalId,'thread_id',500),from,subject,body:scan.redacted,received_at:clean(input.received_at,'received_at',50),prompt_injection_suspected:scan.prompt_injection_suspected,source_checksum:crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex')};}
function deterministicClassification(message){const text=`${message.subject} ${message.body}`.toLowerCase();const priority=/\b(outage|security incident|urgent|deadline today)\b/.test(text)?'high':/\b(invoice|contract|meeting)\b/.test(text)?'normal':'low';const category=/\b(invoice|payment)\b/.test(text)?'finance':/\b(error|outage|support)\b/.test(text)?'support':'general';return{category,priority,confidence:.65,evidence:[`deterministic keyword policy v1`],requires_human_review:true};}
function validateDraft(input){if(!Array.isArray(input.to)||input.to.length===0)throw new TriageError('at least one recipient is required');if(input.to.length>20)throw new TriageError('recipient limit exceeded');const recipients=input.to.map(v=>clean(v,'recipient',320).toLowerCase());if(recipients.some(v=>!/^\S+@\S+\.\S+$/.test(v)))throw new TriageError('invalid recipient');if(input.bcc?.length)throw new TriageError('BCC is disabled for governed sends');return{to:[...new Set(recipients)],cc:Array.isArray(input.cc)?[...new Set(input.cc.map(String))]:[],subject:clean(input.subject,'subject',1000),body:inspectUntrustedContent(clean(input.body,'body',100000)).redacted,grounding:Array.isArray(input.grounding)?input.grounding.slice(0,50):[]};}
function assertDraftTransition(from,to){const allowed={draft:['pending_approval'],pending_approval:['approved','rejected'],rejected:['draft'],approved:['queued'],queued:['sent','failed'],failed:['queued'],sent:[]};if(!(allowed[from]||[]).includes(to))throw new TriageError(`draft transition ${from} -> ${to} is not allowed`);}
function assertApproval(actorId,createdBy,role){if(!['reviewer','admin'].includes(role))throw new TriageError('reviewer role required','FORBIDDEN');if(String(actorId)===String(createdBy))throw new TriageError('draft creator cannot approve their own external send','SEPARATION_OF_DUTIES');}
module.exports={TriageError,inspectUntrustedContent,validateInbound,deterministicClassification,validateDraft,assertDraftTransition,assertApproval};
